# Generated by Django 5.1.7 on 2025-04-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_subtotal_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="iva",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="iva"
            ),
        ),
    ]
