# Generated by Django 5.1.7 on 2025-04-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creation_date",
            field=models.DateField(
                auto_created=True, null=True, verbose_name="fecha_de_creacion"
            ),
        ),
    ]
